/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSignedInRouteImport } from './routes/_layout/_signedIn'
import { Route as LayoutPlansRouteImport } from './routes/_layout/plans'
import { Route as LayoutPrivacyRouteImport } from './routes/_layout/privacy'
import { Route as LayoutTermsRouteImport } from './routes/_layout/terms'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as LayoutSignedInAccountRouteImport } from './routes/_layout/_signedIn/account'
import { Route as LayoutSignedInActivityRouteImport } from './routes/_layout/_signedIn/activity'
import { Route as LayoutSignedInAdminRouteImport } from './routes/_layout/_signedIn/admin'
import { Route as LayoutProfilesUserIdRouteImport } from './routes/_layout/profiles.$userId'
import { Route as LayoutTeamsIndexRouteImport } from './routes/_layout/teams.index'
import { Route as LayoutTeamsTeamIdRouteImport } from './routes/_layout/teams.$teamId'
import { Route as LayoutTopicsTopicIdRouteImport } from './routes/_layout/topics.$topicId'
import { Route as LayoutSignedInMcpConsentRouteImport } from './routes/_layout/_signedIn/mcp.consent'
import { Route as LayoutTopicsTopicIdTopicSlugRouteImport } from './routes/_layout/topics.$topicId_.$topicSlug'
import { Route as LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRouteImport } from './routes/_layout/topics.$topicId_.$topicSlug_.episodes.$season.$episodeNumber'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignedInRoute = LayoutSignedInRouteImport.update({
  id: '/_signedIn',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlansRoute = LayoutPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPrivacyRoute = LayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTermsRoute = LayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LayoutRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSignedInAccountRoute = LayoutSignedInAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => LayoutSignedInRoute,
} as any)
const LayoutSignedInActivityRoute = LayoutSignedInActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LayoutSignedInRoute,
} as any)
const LayoutSignedInAdminRoute = LayoutSignedInAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutSignedInRoute,
} as any)
const LayoutProfilesUserIdRoute = LayoutProfilesUserIdRouteImport.update({
  id: '/profiles/$userId',
  path: '/profiles/$userId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsIndexRoute = LayoutTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsTeamIdRoute = LayoutTeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTopicsTopicIdRoute = LayoutTopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignedInMcpConsentRoute =
  LayoutSignedInMcpConsentRouteImport.update({
    id: '/mcp/consent',
    path: '/mcp/consent',
    getParentRoute: () => LayoutSignedInRoute,
  } as any)
const LayoutTopicsTopicIdTopicSlugRoute =
  LayoutTopicsTopicIdTopicSlugRouteImport.update({
    id: '/topics/$topicId_/$topicSlug',
    path: '/topics/$topicId/$topicSlug',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute =
  LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRouteImport.update({
    id: '/topics/$topicId_/$topicSlug_/episodes/$season/$episodeNumber',
    path: '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/plans': typeof LayoutPlansRoute
  '/privacy': typeof LayoutPrivacyRoute
  '/terms': typeof LayoutTermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/account': typeof LayoutSignedInAccountRoute
  '/activity': typeof LayoutSignedInActivityRoute
  '/admin': typeof LayoutSignedInAdminRoute
  '/profiles/$userId': typeof LayoutProfilesUserIdRoute
  '/teams/$teamId': typeof LayoutTeamsTeamIdRoute
  '/topics/$topicId': typeof LayoutTopicsTopicIdRoute
  '/teams/': typeof LayoutTeamsIndexRoute
  '/mcp/consent': typeof LayoutSignedInMcpConsentRoute
  '/topics/$topicId/$topicSlug': typeof LayoutTopicsTopicIdTopicSlugRoute
  '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber': typeof LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/': typeof LayoutIndexRoute
  '/plans': typeof LayoutPlansRoute
  '/privacy': typeof LayoutPrivacyRoute
  '/terms': typeof LayoutTermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/account': typeof LayoutSignedInAccountRoute
  '/activity': typeof LayoutSignedInActivityRoute
  '/admin': typeof LayoutSignedInAdminRoute
  '/profiles/$userId': typeof LayoutProfilesUserIdRoute
  '/teams/$teamId': typeof LayoutTeamsTeamIdRoute
  '/topics/$topicId': typeof LayoutTopicsTopicIdRoute
  '/teams': typeof LayoutTeamsIndexRoute
  '/mcp/consent': typeof LayoutSignedInMcpConsentRoute
  '/topics/$topicId/$topicSlug': typeof LayoutTopicsTopicIdTopicSlugRoute
  '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber': typeof LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/_signedIn': typeof LayoutSignedInRouteWithChildren
  '/_layout/plans': typeof LayoutPlansRoute
  '/_layout/privacy': typeof LayoutPrivacyRoute
  '/_layout/terms': typeof LayoutTermsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_signedIn/account': typeof LayoutSignedInAccountRoute
  '/_layout/_signedIn/activity': typeof LayoutSignedInActivityRoute
  '/_layout/_signedIn/admin': typeof LayoutSignedInAdminRoute
  '/_layout/profiles/$userId': typeof LayoutProfilesUserIdRoute
  '/_layout/teams/$teamId': typeof LayoutTeamsTeamIdRoute
  '/_layout/topics/$topicId': typeof LayoutTopicsTopicIdRoute
  '/_layout/teams/': typeof LayoutTeamsIndexRoute
  '/_layout/_signedIn/mcp/consent': typeof LayoutSignedInMcpConsentRoute
  '/_layout/topics/$topicId_/$topicSlug': typeof LayoutTopicsTopicIdTopicSlugRoute
  '/_layout/topics/$topicId_/$topicSlug_/episodes/$season/$episodeNumber': typeof LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/plans'
    | '/privacy'
    | '/terms'
    | '/invite/$token'
    | '/account'
    | '/activity'
    | '/admin'
    | '/profiles/$userId'
    | '/teams/$teamId'
    | '/topics/$topicId'
    | '/teams/'
    | '/mcp/consent'
    | '/topics/$topicId/$topicSlug'
    | '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/'
    | '/plans'
    | '/privacy'
    | '/terms'
    | '/invite/$token'
    | '/account'
    | '/activity'
    | '/admin'
    | '/profiles/$userId'
    | '/teams/$teamId'
    | '/topics/$topicId'
    | '/teams'
    | '/mcp/consent'
    | '/topics/$topicId/$topicSlug'
    | '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_layout/_signedIn'
    | '/_layout/plans'
    | '/_layout/privacy'
    | '/_layout/terms'
    | '/invite/$token'
    | '/_layout/'
    | '/_layout/_signedIn/account'
    | '/_layout/_signedIn/activity'
    | '/_layout/_signedIn/admin'
    | '/_layout/profiles/$userId'
    | '/_layout/teams/$teamId'
    | '/_layout/topics/$topicId'
    | '/_layout/teams/'
    | '/_layout/_signedIn/mcp/consent'
    | '/_layout/topics/$topicId_/$topicSlug'
    | '/_layout/topics/$topicId_/$topicSlug_/episodes/$season/$episodeNumber'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_signedIn': {
      id: '/_layout/_signedIn'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutSignedInRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/plans': {
      id: '/_layout/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof LayoutPlansRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/privacy': {
      id: '/_layout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof LayoutPrivacyRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/terms': {
      id: '/_layout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof LayoutTermsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_signedIn/account': {
      id: '/_layout/_signedIn/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof LayoutSignedInAccountRouteImport
      parentRoute: typeof LayoutSignedInRoute
    }
    '/_layout/_signedIn/activity': {
      id: '/_layout/_signedIn/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof LayoutSignedInActivityRouteImport
      parentRoute: typeof LayoutSignedInRoute
    }
    '/_layout/_signedIn/admin': {
      id: '/_layout/_signedIn/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutSignedInAdminRouteImport
      parentRoute: typeof LayoutSignedInRoute
    }
    '/_layout/profiles/$userId': {
      id: '/_layout/profiles/$userId'
      path: '/profiles/$userId'
      fullPath: '/profiles/$userId'
      preLoaderRoute: typeof LayoutProfilesUserIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/': {
      id: '/_layout/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof LayoutTeamsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams/$teamId': {
      id: '/_layout/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof LayoutTeamsTeamIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/topics/$topicId': {
      id: '/_layout/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof LayoutTopicsTopicIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_signedIn/mcp/consent': {
      id: '/_layout/_signedIn/mcp/consent'
      path: '/mcp/consent'
      fullPath: '/mcp/consent'
      preLoaderRoute: typeof LayoutSignedInMcpConsentRouteImport
      parentRoute: typeof LayoutSignedInRoute
    }
    '/_layout/topics/$topicId_/$topicSlug': {
      id: '/_layout/topics/$topicId_/$topicSlug'
      path: '/topics/$topicId/$topicSlug'
      fullPath: '/topics/$topicId/$topicSlug'
      preLoaderRoute: typeof LayoutTopicsTopicIdTopicSlugRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/topics/$topicId_/$topicSlug_/episodes/$season/$episodeNumber': {
      id: '/_layout/topics/$topicId_/$topicSlug_/episodes/$season/$episodeNumber'
      path: '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber'
      fullPath: '/topics/$topicId/$topicSlug/episodes/$season/$episodeNumber'
      preLoaderRoute: typeof LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutSignedInRouteChildren {
  LayoutSignedInAccountRoute: typeof LayoutSignedInAccountRoute
  LayoutSignedInActivityRoute: typeof LayoutSignedInActivityRoute
  LayoutSignedInAdminRoute: typeof LayoutSignedInAdminRoute
  LayoutSignedInMcpConsentRoute: typeof LayoutSignedInMcpConsentRoute
}

const LayoutSignedInRouteChildren: LayoutSignedInRouteChildren = {
  LayoutSignedInAccountRoute: LayoutSignedInAccountRoute,
  LayoutSignedInActivityRoute: LayoutSignedInActivityRoute,
  LayoutSignedInAdminRoute: LayoutSignedInAdminRoute,
  LayoutSignedInMcpConsentRoute: LayoutSignedInMcpConsentRoute,
}

const LayoutSignedInRouteWithChildren = LayoutSignedInRoute._addFileChildren(
  LayoutSignedInRouteChildren,
)

interface LayoutRouteChildren {
  LayoutSignedInRoute: typeof LayoutSignedInRouteWithChildren
  LayoutPlansRoute: typeof LayoutPlansRoute
  LayoutPrivacyRoute: typeof LayoutPrivacyRoute
  LayoutTermsRoute: typeof LayoutTermsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfilesUserIdRoute: typeof LayoutProfilesUserIdRoute
  LayoutTeamsTeamIdRoute: typeof LayoutTeamsTeamIdRoute
  LayoutTopicsTopicIdRoute: typeof LayoutTopicsTopicIdRoute
  LayoutTeamsIndexRoute: typeof LayoutTeamsIndexRoute
  LayoutTopicsTopicIdTopicSlugRoute: typeof LayoutTopicsTopicIdTopicSlugRoute
  LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute: typeof LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutSignedInRoute: LayoutSignedInRouteWithChildren,
  LayoutPlansRoute: LayoutPlansRoute,
  LayoutPrivacyRoute: LayoutPrivacyRoute,
  LayoutTermsRoute: LayoutTermsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfilesUserIdRoute: LayoutProfilesUserIdRoute,
  LayoutTeamsTeamIdRoute: LayoutTeamsTeamIdRoute,
  LayoutTopicsTopicIdRoute: LayoutTopicsTopicIdRoute,
  LayoutTeamsIndexRoute: LayoutTeamsIndexRoute,
  LayoutTopicsTopicIdTopicSlugRoute: LayoutTopicsTopicIdTopicSlugRoute,
  LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute:
    LayoutTopicsTopicIdTopicSlugEpisodesSeasonEpisodeNumberRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
