import Markdown from "markdown-to-jsx"
import { AnchorLink } from "@/components/common/AnchorLink"

// map the terms markdown to a readable legal-page typography: display-font section headings, foreground body.
// auto-linking stays off so bare domains stay plain text. the contact emails are explicit mailto links via AnchorLink
const TERMS_MARKDOWN_OPTIONS = {
	disableAutoLink: true,
	overrides: {
		h2: { props: { className: "font-display mt-8 mb-1 text-lg" } },
		p: { props: { className: "mt-3 text-sm leading-relaxed" } },
		ul: { props: { className: "mt-3 list-disc space-y-1.5 pl-5 text-sm leading-relaxed" } },
		li: { props: { className: "leading-relaxed" } },
		a: { component: AnchorLink, props: { className: "text-link hover:underline" } },
	},
} as const

// the terms of service body, below the title
const TERMS_BODY = `## 1. Agreement

These terms are a contract between you and CarlNotes ("we", "us") covering carlnotes.com and the hosted CarlNotes service. By creating an account or using the service, you accept them. If you do not accept them, do not use the service.

## 2. Open source and self-hosting

The CarlNotes source code is released under the AGPL-3.0 license. The AGPL-3.0 license governs the code. These terms govern only the hosted service at carlnotes.com.

If you run your own instance, you may do anything the AGPL-3.0 license permits. You operate that instance and you are responsible for it. We provide no support, no warranty, and no liability for self-hosted deployments.

## 3. Eligibility and accounts

You are responsible for your account credentials and for everything done under your account. Tell us promptly at [support@carlnotes.com](mailto:support@carlnotes.com) if you suspect unauthorized access. One person per account. Do not share logins.

## 4. What the service does

CarlNotes scans public web sources on a schedule, scores what it finds against context documents you supply, and delivers a feed of items to read, watch, or listen to.

Findings are links and short summaries pointing to content published by other people. We do not own that content, we do not host it, and pointing to it is not an endorsement of it. Follow the link for the original.

Scores, summaries, scan reports, and audio briefings are generated by AI. They can be inaccurate, incomplete, or misleading. Do not rely on them for medical, legal, financial, or other professional decisions. Verify anything that matters against the source.

## 5. Your content

You keep ownership of your topics, context documents, attachments, and everything else you put in.

You grant us a limited license to store, process, transmit, and display that content, and to send it to our AI providers, only as needed to run the service for you. If you publish a topic, that license extends to showing the published parts to anyone who views or follows it. Content from a connected authenticated source is an exception: it is used only to inform scoring and search on your own private topics, and is never displayed to anyone else or included in any published or shared topic. The license ends when you delete the content, except for backup copies that expire on our normal schedule.

You promise that you have the right to upload what you upload, and that it does not infringe anyone's rights or break any law.

We do not use your content to train our own models.

## 5.1 Sharing and connected sources

You may keep a topic private, share it by invitation, or make it public. Two rules govern connected authenticated sources such as an email account:

- A topic that uses a connected authenticated source can only be private. If you change such a topic to invite-only or public, its connected sources are automatically disabled first.
- Public and invite-only topics use public sources only. Content from a connected account never appears in any shared or public feed and is never visible to other users; it only shapes how findings are scored and searched on your own private topics.

When you invite someone to a topic, they gain access only after they accept the invitation, and they see only findings from scans that run after they accept, never the topic's earlier history.

## 6. Acceptable use

Do not:

- Break the law, or use the service to help anyone else break the law
- Upload content you do not have the rights to
- Configure sources that bypass a paywall, login wall, or access control you do not have credentials for
- Connect an account you do not own or are not authorized to use
- Ignore a site's terms, robots directives, or rate limits through the service
- Attempt to overload, probe, reverse engineer, or circumvent limits on the service
- Resell, rent, or white-label the hosted service, or use it to build a directly competing product
- Use the service to generate spam, harassment, malware, or deceptive content
- Publish a topic that promotes illegal activity, harassment, hate, or sexual content involving minors
- Scrape or bulk-export other users' public feeds through automated means

We may suspend or terminate an account that breaks these rules, with notice where practical and without notice where the harm is immediate.

## 7. Plans, limits, and billing

Free trials, plan tiers, and usage limits are described on our pricing page and may change with notice.

Scheduled scans run at your topic's frequency. Manual scans are metered per plan.

When paid plans are live:

- Subscriptions bill in advance on a recurring basis until cancelled
- Prices are in US dollars and exclude taxes, which you are responsible for
- Cancel at any time. Access continues to the end of the paid period
- Fees already paid are non-refundable except where the law requires otherwise
- Without a payment method on file, usage past your limit is rejected instead of being billed
- With a payment method on file, usage past your limit may be billed as metered overage at the posted rate
- Failed payments may lead to suspension after notice
- We will give at least 30 days' notice before a price increase applies to you

## 8. Availability

The service is provided as is and may change. We may add, alter, or remove features, and we may suspend the service for maintenance. There is no uptime commitment unless we have signed a separate agreement with you.

CarlNotes depends on third-party sources and APIs. Sources can break, change terms, or go away. We are not responsible when they do.

## 9. Termination

You may delete your account at any time. We may suspend or close an account for a breach of these terms, for a legal requirement, or if we discontinue the service. If we discontinue the service, we will give reasonable notice and a window to export your data.

On termination, your right to use the service ends and your data is deleted on the schedule in the Privacy Policy. Sections 5, 10, 11, 12, and 14 survive.

## 10. Disclaimers

THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE", WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT AI-GENERATED OUTPUT WILL BE ACCURATE.

## 11. Limitation of liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE ARE NOT LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, DATA, OR GOODWILL.

OUR TOTAL LIABILITY FOR ANY CLAIM IS LIMITED TO THE GREATER OF THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM, OR ONE HUNDRED US DOLLARS.

Some jurisdictions do not allow these limits. Where that is the case, they apply to the fullest extent permitted.

## 12. Indemnity

You agree to defend and hold us harmless from claims arising out of your content, your use of the service, or your breach of these terms.

## 13. Copyright complaints

If you believe content on the hosted service infringes your copyright, send a notice to [support@carlnotes.com](mailto:support@carlnotes.com) with the work, the location, your contact details, a good-faith statement, and your signature. We remove infringing material and terminate repeat infringers.

Note that findings link to third-party content. Requests about the underlying content should go to the site hosting it.

## 14. Governing law and disputes

These terms are governed by the laws of the State of California, without regard to conflict of laws rules. Disputes go to the state or federal courts in San Mateo County, California, and both sides consent to that venue.

## 15. Changes

We may update these terms. We will post the new version here and update the date. If the change is material, we will email account holders at least 30 days before it takes effect. Continuing to use the service after that means you accept the new terms.

## 16. General

These terms plus the Privacy Policy are the entire agreement between us. If a provision is unenforceable, the rest stays in force. Our not enforcing a provision is not a waiver of it. You may not assign these terms. We may assign them in a merger or sale of the business.

## Contact

[support@carlnotes.com](mailto:support@carlnotes.com)`

/**
 * CarlNotes' terms of service for the hosted service.
 */
export function TermsPage() {
	return (
		<main className="mx-auto max-w-3xl px-4 py-8">
			{/* the title and the effective / last-updated dates */}
			<h1 className="font-display text-2xl">Terms of Service</h1>
			<p className="text-muted-foreground mt-2 text-sm">Effective date: July 24, 2026 · Last updated: July 24, 2026</p>
			{/* the numbered sections, rendered from the markdown body */}
			<Markdown options={TERMS_MARKDOWN_OPTIONS}>{TERMS_BODY}</Markdown>
		</main>
	)
}
